const bcrypt = require("bcryptjs");

const User = require("../models/User");

async function userSeeder() {
  await User.sync({ force: true });
  console.log("Se restablecieron las tablas de usuarios");

  const hashedPassword = await bcrypt.hash("password123", 10);

  const newUsers = [
    {
      firstname: "user",
      lastname: "user",
      email: "userprueba@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "123-456-7890",
      country: "Uruguay",
      state: "Montevideo",
      city: "Montevideo",
      address: "123 User St",
      zip: 11000,
    },
    {
      firstname: "Mario",
      lastname: "Pascual",
      email: "paquitoborches@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "234-567-8901",
      country: "Uruguay",
      state: "Canelones",
      city: "Las Piedras",
      address: "456 Mario Ave",
      zip: 91000,
    },
    {
      firstname: "Alvaro",
      lastname: "Olmos",
      email: "pajarito24@outlook.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "345-678-9012",
      country: "Uruguay",
      state: "San José",
      city: "Libertad",
      address: "789 Alvaro Rd",
      zip: 80000,
    },
    {
      firstname: "Hugo",
      lastname: "Campana",
      email: "elcampanero23@hotmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "456-789-0123",
      country: "Uruguay",
      state: "Colonia",
      city: "Carmelo",
      address: "1011 Hugo Blvd",
      zip: 70100,
    },
    {
      firstname: "José",
      lastname: "Cordero",
      email: "josecorderouy@adinet.com.uy",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "567-890-1234",
      country: "Uruguay",
      state: "Florida",
      city: "Florida",
      address: "1213 José Ave",
      zip: 94000,
    },
    {
      firstname: "Gabriela",
      lastname: "Martínez",
      email: "martinolagaby@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "678-901-2345",
      country: "Uruguay",
      state: "Rocha",
      city: "La Paloma",
      address: "1415 Gabriela St",
      zip: 27001,
    },
    {
      firstname: "Laura",
      lastname: "Cabrera",
      email: "cabritosxsiempre@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "789-012-3456",
      country: "Uruguay",
      state: "Maldonado",
      city: "Piriápolis",
      address: "1617 Laura Ln",
      zip: 20200,
    },
    {
      firstname: "Luis",
      lastname: "Paz",
      email: "drluispazmilka@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "890-123-4567",
      country: "Uruguay",
      state: "Artigas",
      city: "Bella Unión",
      address: "1819 Luis Blvd",
      zip: 55000,
    },
    {
      firstname: "Carlos",
      lastname: "Pereyra",
      email: "carpinchorojo@hotmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "901-234-5678",
      country: "Uruguay",
      state: "Rivera",
      city: "Rivera",
      address: "2021 Carlos St",
      zip: 40000,
    },
    {
      firstname: "Myriam",
      lastname: "Herrera",
      email: "cancioneslargas12@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "012-345-6789",
      country: "Uruguay",
      state: "Tacuarembó",
      city: "Paso de los Toros",
      address: "2223 Myriam Rd",
      zip: 45100,
    },
    {
      firstname: "Clara",
      lastname: "Silvera",
      email: "claritacandycandy@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "123-456-7890",
      country: "Uruguay",
      state: "Lavalleja",
      city: "Minas",
      address: "2425 Clara Ave",
      zip: 30000,
    },
    {
      firstname: "Maria",
      lastname: "Moreira",
      email: "moritaarzua@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "234-567-8901",
      country: "Uruguay",
      state: "Durazno",
      city: "Durazno",
      address: "2627 Maria St",
      zip: 97000,
    },
    {
      firstname: "Claudia",
      lastname: "Alonso",
      email: "arquitecturaantigua@lbtours.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "345-678-9012",
      country: "Uruguay",
      state: "Paysandú",
      city: "Guichón",
      address: "2829 Claudia Blvd",
      zip: 60001,
    },
    {
      firstname: "Federico",
      lastname: "Cedres",
      email: "fico.cedres14@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "456-789-0123",
      country: "Uruguay",
      state: "Salto",
      city: "Salto",
      address: "3031 Federico Ln",
      zip: 50000,
    },
    {
      firstname: "Beatriz",
      lastname: "Ferreira",
      email: "betinaferreira@hotmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "567-890-1234",
      country: "Uruguay",
      state: "Treinta y Tres",
      city: "Vergara",
      address: "3233 Beatriz Rd",
      zip: 33002,
    },
    {
      firstname: "Daniela",
      lastname: "Acosta",
      email: "alondravoladora@yahoo.es",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "678-901-2345",
      country: "Uruguay",
      state: "Cerro Largo",
      city: "Melo",
      address: "3435 Daniela St",
      zip: 37000,
    },
    {
      firstname: "Alvaro",
      lastname: "Vazquez",
      email: "asasotiaga@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "789-012-3456",
      country: "Uruguay",
      state: "Flores",
      city: "Trinidad",
      address: "3637 Alvaro Blvd",
      zip: 85000,
    },
    {
      firstname: "Vilma",
      lastname: "Lema",
      email: "levima87@gmail.com",
      password: hashedPassword,
      avatar: "/img/avatar.png",
      phone: "890-123-4567",
      country: "Uruguay",
      state: "Río Negro",
      city: "Fray Bentos",
      address: "3839 Vilma Ln",
      zip: 65000,
    },
  ];

  await User.bulkCreate(newUsers);
  console.log("¡Las tablas de usuario fueron creadas!");
}

module.exports = userSeeder;
